import type { AppLocale } from '@/components/AppPreferences';

const EXACT_TRANSLATIONS: Record<string, string> = {
  'กำลังโหลด...': 'Loading...',
  'กำลังโหลด…': 'Loading...',
  'เข้าสู่ระบบ': 'Log in',
  'ออกจากระบบ': 'Log out',
  'เริ่มต้นใช้งาน': 'Get Started',
  'ตลาด': 'Marketplace',
  'เช็คคนโกง': 'Scam Check',
  'ประกาศหาสินค้า': 'Wanted Board',
  'บริการผ่านคนกลาง': 'Escrow Services',
  'สมัครสมาชิก': 'Join',
  'สมัคร': 'Join',
  'ช่วยเหลือ': 'Help',
  'บริการ': 'Services',
  'การเงิน': 'Finance',
  'ภาพรวม': 'Overview',
  'ผู้ขาย': 'Seller',
  'ผู้ซื้อ': 'Buyer',
  'คนกลาง': 'Middleman',
  'ข้อพิพาท': 'Dispute',
  'ดีล & ข้อพิพาท': 'Deals & Disputes',
  'ตรวจสอบเนื้อหา': 'Moderation',
  'ผู้ใช้ทั้งหมด': 'Users',
  'ควบคุมบริการ': 'Service Controls',
  'ค่าธรรมเนียม': 'Fees',
  'สถานะระบบ': 'System Status',
  'นโยบายความเป็นส่วนตัว': 'Privacy Policy',
  'เงื่อนไขการใช้งาน': 'Terms of Use',
  'นโยบายคุกกี้': 'Cookie Policy',
  'คำถามที่พบบ่อย': 'FAQ',
  'ติดต่อทีมงาน': 'Contact Support',
  'วิธีใช้งาน': 'How It Works',
  'ความเป็นส่วนตัว': 'Privacy',
  'คุกกี้': 'Cookies',
  'เช็คพัสดุ': 'Track Parcel',
  'ผู้ให้บริการโลจิสติกส์': 'Logistics Provider',
  'เลขพัสดุ': 'Tracking Number',
  'แพ็คสินค้า': 'Packing',
  'โลจิสติกส์': 'Logistics',
  'สลิปและเลขอ้างอิง': 'Slip & Reference',
  'ข้อเสนอแนะเพิ่มเติม': 'Additional Feedback',
  'เหตุผลที่อยากแนะนำ': 'Recommended Reasons',
  'ส่งรีวิว': 'Submit Review',
  'แตะดาวให้ครบทุกรายการก่อนส่ง': 'Rate every item before submitting',
  'ขอบคุณสำหรับรีวิว': 'Thank you for your review',
  'ติดต่อทีมงาน มีข้อความใหม่': 'Support has a new message',
  'ติดต่อทีมงาน มีสายเข้า': 'Support has an incoming call',
  'กลับหน้าหลัก': 'Back to Home',
  'ดูหน้าเว็บ ↗': 'Open Website ↗',
  'การแจ้งเตือน': 'Notifications',
  'Admin': 'Admin',
};

const PHRASE_REPLACEMENTS: Array<[string, string]> = [
  ['ซื้อขายผ่านกลาง', 'Escrow Trade'],
  ['นัดรับผ่านกลาง', 'Meetup Escrow'],
  ['ฝากขายผ่านกลาง', 'Consign with Escrow'],
  ['บริการนัดออนไซต์', 'On-site Service'],
  ['สมัครเป็นผู้ขาย', 'Become a Seller'],
  ['สมัครเป็นคนกลาง', 'Become a Middleman'],
  ['ระบบคุ้มครองดีล', 'Protected Deal System'],
  ['ซื้อขายมั่นใจด้วยระบบตัวกลาง', 'Secure trading with escrow protection'],
  ['รอศูนย์กลางยืนยันรับเงิน', 'Awaiting admin payment confirmation'],
  ['กำลังตรวจสอบสิทธิ์...', 'Checking access...'],
  ['เข้าสู่โปรไฟล์', 'Profile'],
  ['ดีลของฉัน / ประวัติ', 'My Deals / History'],
  ['บอร์ดผู้ขาย', 'Seller Board'],
  ['บอร์ดคนกลาง', 'Middleman Board'],
  ['แชทลูกค้า', 'Customer Chat'],
  ['รายงานคนโกง', 'Scam Reports'],
  ['งานนัดออนไซต์', 'On-site Jobs'],
  ['เงินค้ำประกันคนกลาง', 'Middleman Deposits'],
  ['รอตรวจสอบ', 'Pending Review'],
  ['ยืนยันแล้ว', 'Confirmed'],
  ['กำลังแพ็ค', 'Packing'],
  ['รอเลขพัสดุ', 'Awaiting tracking number'],
  ['ได้เลขพัสดุแล้ว', 'Tracking number received'],
  ['รอตรวจหลักฐาน', 'Awaiting evidence review'],
  ['รอยืนยันรับ', 'Awaiting receive confirmation'],
  ['รอผู้ซื้อ', 'Awaiting buyer'],
  ['รอผู้ขาย', 'Awaiting seller'],
  ['เสร็จสมบูรณ์', 'Completed'],
  ['ยกเลิก', 'Cancelled'],
  ['มีปัญหา/ข้อพิพาท', 'Issue / Dispute'],
  ['พร้อมนัดเจอ', 'Ready for meetup'],
  ['รอโอนเงิน', 'Awaiting payment'],
  ['ตรวจสอบเนื้อหา', 'Content Moderation'],
  ['ตรวจสลิป', 'Verify slip'],
  ['สลิปผู้ซื้อ', 'Buyer slip'],
  ['สลิปผู้ขาย', 'Seller slip'],
  ['สลิปค่าบริการ', 'Service fee slip'],
  ['ถูกต้อง', 'Correct'],
  ['ไม่ถูกต้อง', 'Incorrect'],
  ['กรุณา', 'Please'],
  ['บันทึก', 'Save'],
  ['แก้ไข', 'Edit'],
  ['ลบ', 'Delete'],
  ['คืนประกาศ', 'Restore'],
  ['ปิดประกาศ', 'Hide listing'],
  ['แสดงในตลาด', 'Visible in marketplace'],
  ['ถอดแล้ว', 'Removed'],
  ['เปิดอยู่', 'Active'],
  ['ปิดแล้ว', 'Closed'],
  ['ข้อความ', 'Message'],
  ['ส่งข้อความ', 'Send message'],
  ['พิมพ์ข้อความ', 'Type a message'],
  ['ขอให้พนักงานโทรกลับ', 'Request a callback'],
  ['วางสาย', 'Hang up'],
  ['เปิดไมค์', 'Unmute'],
  ['ปิดไมค์', 'Mute'],
  ['รับสาย', 'Answer call'],
  ['ปฏิเสธสาย', 'Decline call'],
  ['กำลังเชื่อมต่อสาย…', 'Connecting call...'],
  ['เชื่อมต่อไม่สำเร็จ', 'Connection failed'],
  ['สายกำลังคุยอยู่', 'Call in progress'],
  ['กำลังส่ง...', 'Sending...'],
  ['อ่านแล้ว', 'Read'],
  ['รอคืนเงิน', 'Awaiting refund'],
  ['คืนเงินผู้ซื้อ', 'Refund buyer'],
  ['ยืนยันรับเงิน', 'Confirm payment'],
  ['โอนเงินค่าสินค้า', 'Transfer item payment'],
  ['โอนเงินค่าคนกลาง', 'Transfer middleman fee'],
  ['แพลตฟอร์มซื้อขายปลอดภัยด้วยระบบตัวกลาง ช่วยลดความเสี่ยงในการโอนเงิน ตรวจรับสินค้า และติดตามดีลได้ในที่เดียว', 'A secure escrow marketplace that reduces transfer risk, supports item verification, and keeps every deal trackable in one place.'],
  ['สงสัยว่าจะโดนโกง? เช็คก่อนโอน', 'Think it might be a scam? Check before you pay'],
  ['ตรวจสอบเลย', 'Check Now'],
  ['สมาชิกทั้งหมด', 'Total Members'],
  ['ผู้ขายในระบบ', 'Registered Sellers'],
  ['คนกลางผ่านการรับรอง', 'Verified Middlemen'],
  ['ดีลสำเร็จปลอดภัย', 'Completed Protected Deals'],
  ['มูลค่าที่คุ้มครอง', 'Protected Value'],
  ['ความพึงพอใจผู้ใช้', 'User Satisfaction'],
  ['ทุกปัญหาการซื้อขาย เรามีทางแก้ให้', 'We design services for real trading problems'],
  ['เลื่อนดูบริการที่ออกแบบมาแก้ปัญหาที่คนซื้อ–ขายเจอบ่อยที่สุด พร้อมข้อดีที่คุณจะได้รับ', 'Browse services built to solve the most common buyer-seller risks, with clear benefits for both sides.'],
];

export function translateText(input: string, locale: AppLocale): string {
  if (locale === 'th') return input;
  if (!input || !/[ก-๙]/.test(input)) return input;

  const leading = input.match(/^\s*/)?.[0] || '';
  const trailing = input.match(/\s*$/)?.[0] || '';
  const raw = input.trim();
  const exact = EXACT_TRANSLATIONS[raw];
  if (exact) return `${leading}${exact}${trailing}`;

  let translated = raw;
  for (const [from, to] of PHRASE_REPLACEMENTS) {
    if (translated.includes(from)) translated = translated.split(from).join(to);
  }

  const tokenMap: Array<[RegExp, string]> = [
    [/\bดีล\b/g, 'deal'],
    [/ผู้ซื้อ/g, 'Buyer'],
    [/ผู้ขาย/g, 'Seller'],
    [/คนกลาง/g, 'Middleman'],
    [/แพลตฟอร์ม/g, 'Platform'],
    [/ระบบ/g, 'system'],
    [/สถานะ/g, 'status'],
    [/รายการ/g, 'item'],
    [/คะแนน/g, 'rating'],
    [/รีวิว/g, 'review'],
    [/ข้อเสนอแนะ/g, 'feedback'],
    [/เหตุผล/g, 'reason'],
    [/พร้อม/g, 'ready'],
    [/ชำระเงิน/g, 'payment'],
    [/สลิป/g, 'slip'],
    [/เลขอ้างอิง/g, 'reference'],
    [/หลักฐาน/g, 'evidence'],
    [/สินค้า/g, 'item'],
    [/อัปโหลด/g, 'upload'],
    [/ตรวจสอบ/g, 'verify'],
    [/ยืนยัน/g, 'confirm'],
    [/ไม่บังคับ/g, 'optional'],
    [/ส่ง/g, 'send'],
    [/รับ/g, 'receive'],
    [/ทีมงาน/g, 'support team'],
    [/พนักงาน/g, 'staff'],
    [/รายละเอียด/g, 'details'],
    [/โปรไฟล์/g, 'profile'],
    [/บัญชี/g, 'account'],
    [/ประวัติ/g, 'history'],
    [/ตลาด/g, 'marketplace'],
    [/ผู้ใช้/g, 'user'],
    [/ทั้งหมด/g, 'all'],
    [/บริการ/g, 'service'],
    [/สมัคร/g, 'join'],
    [/แจ้งเตือน/g, 'notifications'],
    [/ค่าสินค้า/g, 'item price'],
    [/ค่าบริการ/g, 'service fee'],
    [/ค่าคนกลาง/g, 'middleman fee'],
    [/แพ็ค/g, 'pack'],
    [/จัดส่ง/g, 'ship'],
    [/เลขพัสดุ/g, 'tracking number'],
    [/ผู้ให้บริการ/g, 'provider'],
    [/โลจิสติกส์/g, 'logistics'],
    [/ขั้นตอน/g, 'step'],
    [/ขั้นที่/g, 'Step'],
    [/จาก/g, 'of'],
    [/หน้าแรก/g, 'home'],
  ];

  for (const [pattern, to] of tokenMap) {
    translated = translated.replace(pattern, to);
  }

  return `${leading}${translated}${trailing}`;
}
