@echo off
echo Clearing git locks...
del /f ".git\index.lock" 2>nul
del /f ".git\HEAD.lock" 2>nul
echo Fixing git config...
git config user.name "kitthanet"
git config user.email "kitthanetfx@gmail.com"
echo Staging all changes...
git add -A
echo Committing...
git commit -m "fix: sync prefs across accounts on profile load + bigger back button + deals dashboards"
echo Pushing...
git push
echo Done!
pause
