@echo off
echo Clearing git locks...
del /f ".git\index.lock" 2>nul
del /f ".git\HEAD.lock" 2>nul
echo Fixing git config...
git config user.name "kitthanet"
git config user.email "kitthanetfx@gmail.com"
echo Staging all changes...
git add -A
echo Committing...
git commit -m "feat: deal room v2 + compact deals schema (22 attrs, evidenceData unified field)"
echo Pushing...
git push
echo Done!
pause
